# Generated by Django 4.2.5 on 2023-09-21 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servico",
            options={"verbose_name": "Serviço", "verbose_name_plural": "Serviços"},
        ),
    ]
