# Generated by Django 4.2.5 on 2023-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_recurso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("lni-package", "Caixa"),
                            ("lni-drop", "Gota de Água"),
                            ("lni-star", "Estrela"),
                        ],
                        max_length=15,
                        verbose_name="Icone",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço"
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "usuarios",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            ("ilimitado", "Ilimitado"),
                        ],
                        verbose_name="Usuários",
                    ),
                ),
                (
                    "armazenamento",
                    models.PositiveIntegerField(
                        choices=[
                            ("10", "10"),
                            ("20", "20"),
                            ("30", "30"),
                            ("40", "40"),
                            ("50", "50"),
                            ("ilimitado", "Ilimitado"),
                        ],
                        verbose_name="Armazenamento",
                    ),
                ),
                ("suporte", models.CharField(max_length=100, verbose_name="Suporte")),
                (
                    "atualizacoes",
                    models.CharField(max_length=100, verbose_name="Atualizações"),
                ),
            ],
            options={
                "verbose_name": "Preço",
                "verbose_name_plural": "Preços",
            },
        ),
    ]
