# Generated by Django 4.2.5 on 2023-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_preco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preco",
            name="armazenamento",
            field=models.CharField(
                choices=[
                    ("10", "10"),
                    ("20", "20"),
                    ("30", "30"),
                    ("40", "40"),
                    ("50", "50"),
                    ("ilimitado", "Ilimitado"),
                ],
                max_length=10,
                verbose_name="Armazenamento",
            ),
        ),
    ]
