# Generated by Django 4.2.5 on 2023-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_plano_usuarios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plano",
            name="usuarios",
            field=models.CharField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    ("ilimitado", "Ilimitado"),
                ],
                max_length=10,
                verbose_name="Usuários",
            ),
        ),
    ]
