# Generated by Django 4.2.5 on 2023-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="avaliacao",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                verbose_name="Avaliação",
            ),
        ),
    ]
